# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true # no longer works with Jekyll 3.0

# Setup
title:               Brad Stachurski
tagline:             'Web Development, Data-Viz, & Entrepreneurship'
description:         "A blog where I write about what I've learned in the fields of Web Development, Data-Viz, & Entrepreneurship that have allowed me to work for myself and travel the world."
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
gems:                [jekyll-paginate]
paginate_path:       "page:num"

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0


markdown: kramdown
highlighter: rogue